# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YapStars' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for YapStars

  pod 'Firebase/Core', '~> 5.20.1'

  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Functions', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Firebase/RemoteConfig', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'

  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'FBSDKCoreKit', '~> 4.39.0'
  pod 'FBSDKLoginKit', '~> 4.39.0'
  pod 'FBSDKShareKit', '~> 4.39.0'
  pod 'TwitterKit', '~> 3.3.0'

  pod 'Fabric', '~> 1.10.1'
  pod 'Crashlytics', '~> 3.13.1'

  pod 'OpenTok', '2.15.3'

  target 'YapStarsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'YapStars-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YapStars-tvOS

  target 'YapStars-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

