# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'YapStars' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YapStars

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'

  pod 'Firebase/AdMob', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Database', '~> 5.20.1'
  pod 'Firebase/Functions', '~> 5.20.1'
  pod 'Firebase/DynamicLinks', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Firebase/RemoteConfig', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'
  pod 'Firebase/Performance', '~> 5.20.1'

  # Crashlytics
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'

  # pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'


    pod 'FBSDKCoreKit', '~> 4.41.0'
    pod 'FBSDKLoginKit', '~> 4.41.0'
    pod 'FBSDKShareKit', '~> 4.41.0'
end
